### ISSUE TITLE
Auth status handler panics if user didn't finish the auth process

### ISSUE THREAD

**Issue by avbasov** [go-pkgz/auth#103]
Hello. First of all, thank you for this awesome lib.

Version: master (v1.18.1-0.20211209053423-949213843b23)

Problem: If the user doesn't finish auth process and return to the previous page:
handler `/auth/user` returns status 200 and null as a response body
handler `/auth/status` panics
```
http: panic serving 127.0.0.1:63736: runtime error: invalid memory address or nil pointer dereference
goroutine 704 [running]:
net/http.(*conn).serve.func1()
        /usr/local/Cellar/go/1.17.6/libexec/src/net/http/server.go:1802 +0xb9
panic({0x2057a40, 0x2f9e580})
        /usr/local/Cellar/go/1.17.6/libexec/src/runtime/panic.go:1047 +0x266
github.com/go-pkgz/auth.(*Service).Handlers.func1({0x2b539438, 0xc0007be780}, 0xc0005b3f00)
        /Users/dv/go/pkg/mod/github.com/go-pkgz/auth@v1.18.1-0.20211209053423-949213843b23/auth.go:199 +0x5ed
net/http.HandlerFunc.ServeHTTP(0xc, {0x2b539438, 0xc0007be780}, 0xc0008c0f8a)
        /usr/local/Cellar/go/1.17.6/libexec/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x2b539438, 0xc0007be780}, 0xc0005b3f00)
        /Users/dv/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x19c
net/http.HandlerFunc.ServeHTTP(0x204d4a0, {0x2b539438, 0xc0007be780}, 0xc0008c0f84)
        /usr/local/Cellar/go/1.17.6/libexec/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc00046cae0, {0x2b539438, 0xc0007be780}, 0xc0005b3f00)
        /Users/dv/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x216
net/http.HandlerFunc.ServeHTTP(0xc00032a280, {0x2b539438, 0xc0007be780}, 0xc0005b3f00)
        /usr/local/Cellar/go/1.17.6/libexec/src/net/http/server.go:2047 +0x2f
github.com/go-chi/cors.(*Cors).Handler.func1({0x2b539438, 0xc0007be780}, 0xc0005b3f00)
        /Users/dv/go/pkg/mod/github.com/go-chi/cors@v1.2.0/cors.go:228 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc0005b3e00, {0x2b539438, 0xc0007be780}, 0x1000000000000d0)
        /usr/local/Cellar/go/1.17.6/libexec/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi/v5/middleware.RequestLogger.func1.1({0x2493fa0, 0xc000656620}, 0xc0005b3e00)
        /Users/dv/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/logger.go:57 +0x18e
net/http.HandlerFunc.ServeHTTP(0x24984d8, {0x2493fa0, 0xc000656620}, 0x2f9dff0)
        /usr/local/Cellar/go/1.17.6/libexec/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc00046cae0, {0x2493fa0, 0xc000656620}, 0xc0005b3c00)
        /Users/dv/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:88 +0x442
net/http.serverHandler.ServeHTTP({0xc0007a19e0}, {0x2493fa0, 0xc000656620}, 0xc0005b3c00)
        /usr/local/Cellar/go/1.17.6/libexec/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0002a0dc0, {0x2498580, 0xc0003fb0b0})
        /usr/local/Cellar/go/1.17.6/libexec/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.17.6/libexec/src/net/http/server.go:3034 +0x4e8
```

Steps to reproduce:

1. Start auth with Google provider.
2. After being redirected to a "Choose an account" screen, return without choosing anything.

**Comment by umputun** [comment]
i have added a couple of extra checks to both /user and /status to make sure the user struct filled (not nil). It is on master, give it a try

**Comment by avbasov** [comment]
Works like a charm. Thank you!
