### ISSUE TITLE
Example server crashes on login abort

### ISSUE THREAD

**Issue by Reeywhaar** [go-pkgz/auth#2]
Examples server's `/private_data` request crashes if oauth login was interrupted.

**Steps to reproduce**
* start example
* navigate to http://127.0.0.1:8080/web
* click on any `login with {provider}`
* close the popped up tab/page without granting access
* refresh main page
* you'll see that iframe with `/private_data` resetted request

In logs you can see:
```
auth-example    | 2018/12/29 04:56:12 [REST] GET - /private_data - 192.168.48.1 - 200 (0) - 195.9µs
auth-example    | 2018/12/29 04:56:12 http: panic serving 192.168.48.1:59624: runtime error: invalid memory address or nil pointer dereference
auth-example    | goroutine 42 [running]:
auth-example    | net/http.(*conn).serve.func1(0xc000140dc0)
auth-example    |       /usr/local/go/src/net/http/server.go:1746 +0xd0
auth-example    | panic(0x82f9e0, 0xbf8f90)
auth-example    |       /usr/local/go/src/runtime/panic.go:513 +0x1b9
auth-example    | github.com/go-pkgz/auth/middleware.(*Authenticator).auth.func2.1(0x922fc0, 0xc0001a3dc0, 0xc0001c6d00)
auth-example    |       /go/pkg/mod/github.com/go-pkgz/auth@v0.0.0-20181229073233-4ee872edfbc1/middleware/auth.go:88 +0x6ad
auth-example    | net/http.HandlerFunc.ServeHTTP(0xc000069920, 0x922fc0, 0xc0001a3dc0, 0xc0001c6d00)
auth-example    |       /usr/local/go/src/net/http/server.go:1964 +0x44
auth-example    | github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc0000aeac0, 0x922fc0, 0xc0001a3dc0, 0xc0001c6d00)
auth-example    |       /go/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/chain.go:31 +0x52
auth-example    | github.com/go-chi/chi.(*Mux).routeHTTP(0xc0000826c0, 0x922fc0, 0xc0001a3dc0, 0xc0001c6d00)
auth-example    |       /go/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:424 +0x239
auth-example    | github.com/go-chi/chi.(*Mux).routeHTTP-fm(0x922fc0, 0xc0001a3dc0, 0xc0001c6d00)
auth-example    |       /go/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:368 +0x48
auth-example    | net/http.HandlerFunc.ServeHTTP(0xc0000673f0, 0x922fc0, 0xc0001a3dc0, 0xc0001c6d00)
auth-example    |       /usr/local/go/src/net/http/server.go:1964 +0x44
auth-example    | github.com/go-pkgz/rest/logger.(*Middleware).Handler.func1(0x923580, 0xc00013cfc0, 0xc0001c6d00)
auth-example    |       /go/pkg/mod/github.com/go-pkgz/rest@v1.1.2/logger/logger.go:93 +0x1cc
auth-example    | net/http.HandlerFunc.ServeHTTP(0xc0000729c0, 0x923580, 0xc00013cfc0, 0xc0001c6d00)
auth-example    |       /usr/local/go/src/net/http/server.go:1964 +0x44
auth-example    | github.com/go-pkgz/rest.Ping.func1(0x923580, 0xc00013cfc0, 0xc0001c6d00)
auth-example    |       /go/pkg/mod/github.com/go-pkgz/rest@v1.1.2/middleware.go:40 +0x68
auth-example    | net/http.HandlerFunc.ServeHTTP(0xc0000729e0, 0x923580, 0xc00013cfc0, 0xc0001c6d00)
auth-example    |       /usr/local/go/src/net/http/server.go:1964 +0x44
auth-example    | github.com/go-pkgz/rest.AppInfo.func1.1(0x923580, 0xc00013cfc0, 0xc0001c6d00)
auth-example    |       /go/pkg/mod/github.com/go-pkgz/rest@v1.1.2/middleware.go:21 +0x1c3
auth-example    | net/http.HandlerFunc.ServeHTTP(0xc000092410, 0x923580, 0xc00013cfc0, 0xc0001c6d00)
auth-example    |       /usr/local/go/src/net/http/server.go:1964 +0x44
auth-example    | github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0000826c0, 0x923580, 0xc00013cfc0, 0xc0001c6c00)
auth-example    |       /go/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:81 +0x293
auth-example    | net/http.serverHandler.ServeHTTP(0xc00006f450, 0x923580, 0xc00013cfc0, 0xc0001c6c00)
auth-example    |       /usr/local/go/src/net/http/server.go:2741 +0xab
auth-example    | net/http.(*conn).serve(0xc000140dc0, 0x923a40, 0xc0001b8580)
auth-example    |       /usr/local/go/src/net/http/server.go:1847 +0x646
auth-example    | created by net/http.(*Server).Serve
auth-example    |       /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by umputun** [comment]
Fixed. Caused by logging part, reported incompatible token (the one used for a handshake) and middleware tried too hard to log non-existent details like user.*

Currently, such aborted login produce expected error message and returns 401

```
2018/12/29 12:46:17 [INFO] run local oauth2 dev server on 8084, redir url=http://127.0.0.1:8080/auth/dev/callback
2018/12/29 12:46:22 [DEBUG] auth failed, invalid kind of token
2018/12/29 12:46:22 [REST] GET - /private - 127.0.0.1 - 401 (13) - 525.159µs  
```
