### ISSUE TITLE
Avatar test failure

### ISSUE THREAD

**Issue by zonescape** [go-pkgz/auth#21]
```
$ go test github.com/go-pkgz/auth/avatar
2019/04/10 13:22:49 [DEBUG] avatar resize(): limit should be greater than 0
2019/04/10 13:22:49 [DEBUG] saved identicon avatar to b3daa77b4c04a9551b8781d03191fe098f325e67.image, user "user1 name"
2019/04/10 13:22:54 request: /avatar/pic
2019/04/10 13:22:54 [DEBUG] avatar resize(): limit should be greater than 0
2019/04/10 13:22:54 [DEBUG] saved avatar from http://127.0.0.1:33537/pic.png to b3daa77b4c04a9551b8781d03191fe098f325e67.image, user "user1 name"
2019/04/10 13:22:54 can't load avatar - can't load avatar some_random_name.image, id: open /tmp/avatars.test/91/some_random_name.image: no such file or directory - 400 -  - /some_random_name.image [caused by auth/avatar/avatar.go:106 avatar.(*Proxy).Handler]
2019/04/10 13:22:54 [WARN] avatar resize(): reader is nil
2019/04/10 13:22:54 [DEBUG] avatar resize(): limit should be greater than 0
2019/04/10 13:22:54 [WARN] avatar resize(): can't decode avatar image, image: unknown format
2019/04/10 13:22:54 [DEBUG] resizing image is smaller that the limit or has 0 size
2019/04/10 13:22:54 [DEBUG] resizing image is smaller that the limit or has 0 size
2019/04/10 13:22:54 [DEBUG] can't get avatar info 'aaaa', can't load avatar's id for aaaa
2019/04/10 13:22:55 [DEBUG] connect to mongo test instance
2019/04/10 13:22:55 [DEBUG] dial mongo [mongo:27017], ssl=false
2019/04/10 13:23:06 [DEBUG] clean test collection test_78663133
--- FAIL: TestGridFS_PutAndGet (10.94s)
    testing.go:70: no MONGO_TEST in env, defaulted to mongodb://mongo:27017
    testing.go:27: 
            Error Trace:    testing.go:27
                                        once.go:44
                                        testing.go:24
                                        gridfs_test.go:87
                                        gridfs_test.go:17
            Error:          Expected nil, but got: &errors.errorString{s:"can't connect to mongo, no reachable servers"}
            Test:           TestGridFS_PutAndGet
            Messages:       failed to dial
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x84cde9]

goroutine 79 [running]:
testing.tRunner.func1(0xc0000e8400)
    /usr/local/go/src/testing/testing.go:830 +0x388
panic(0x8e1ec0, 0xd63990)
    /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/go-pkgz/mongo.(*Connection).WithCustomCollection(0xc000363860, 0xc0003644f0, 0xd, 0xc000865e28, 0x1, 0x466332)
    /home/zonescape/go/pkg/mod/github.com/go-pkgz/mongo@v1.0.0/connection.go:32 +0x29
github.com/go-pkgz/mongo.(*Connection).WithCollection(...)
    /home/zonescape/go/pkg/mod/github.com/go-pkgz/mongo@v1.0.0/connection.go:26
github.com/go-pkgz/mongo.RemoveTestCollection(0xc0000e8400, 0xc000363860)
    /home/zonescape/go/pkg/mod/github.com/go-pkgz/mongo@v1.0.0/testing.go:38 +0xd8
github.com/go-pkgz/mongo.MakeTestConnection(0xc0000e8400, 0x2, 0xc000132b18, 0x45d110)
    /home/zonescape/go/pkg/mod/github.com/go-pkgz/mongo@v1.0.0/testing.go:31 +0x9a
github.com/go-pkgz/auth/avatar.prepGFStore(0xc0000e8400, 0x45d110, 0xc000041f98, 0x4f1999)
    /home/zonescape/go/src2/github.com/go-pkgz/auth/avatar/gridfs_test.go:87 +0x2f
github.com/go-pkgz/auth/avatar.TestGridFS_PutAndGet(0xc0000e8400)
    /home/zonescape/go/src2/github.com/go-pkgz/auth/avatar/gridfs_test.go:17 +0x40
testing.tRunner(0xc0000e8400, 0x988ae8)
    /usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:916 +0x357
FAIL    github.com/go-pkgz/auth/avatar  16.641s
```

PS
Output says something about MongoDB. I don't have MongoDB installed.

**Comment by umputun** [comment]
One of the avatar stores is gridfs (i.e. mongo) and this is the reason why it needs mongo for tests. You can run it locally in a container - `docker run -d -p 27017:27017 mongo:4`. If you want to skip all tests related to gridfs set `MONGO_TEST=skip` in the environment
