### ISSUE TITLE
Telegram auth panics in remark42

### ISSUE THREAD

**Issue by Ksinia** [go-pkgz/auth#90]
I've started [remark42](https://github.com/umputun/remark42) with AUTH_TELEGRAM=true and TELEGRAM_TOKEN set in [compose-dev-frontend.yml](https://github.com/umputun/remark42/blob/master/compose-dev-frontend.yml), and when I open http://127.0.0.1:8080/auth/telegram/login I get 500 Internal Server Error once and then calls to that endpoint just times out. Backend logs:

```
2021/08/05 16:54:36.806 [INFO]  {logger/logger.go:130 logger.(*Middleware).Handler.func1.1} GET - /auth/telegram/login - 127.0.0.1 - 81c21ca5009d - 200 (0) - 76.125µs
2021/08/05 16:54:36.806 [INFO]  {rest/middleware.go:62 rest.Recoverer.func1.1.1} request panic for /auth/telegram/login from 172.23.0.1:58176, assignment to entry in nil map
2021/08/05 16:54:36.806 [INFO]  {rest/middleware.go:64 rest.Recoverer.func1.1.1} goroutine 34 [running]:
runtime/debug.Stack(0x40000d4180, 0xc6acbe, 0x20)
 /usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/go-pkgz/rest.Recoverer.func1.1.1(0xffff5ef669b8, 0x40000d4180, 0x400063a800, 0x11da270, 0x400094a0e0)
 /build/backend/vendor/github.com/go-pkgz/rest/middleware.go:64 +0x198
panic(0xacc220, 0x11b8b70)
 /usr/local/go/src/runtime/panic.go:965 +0x154
github.com/go-pkgz/auth/provider.(*TelegramHandler).LoginHandler(0x400064f0e0, 0x11d9b20, 0x4000596ee0, 0x400063a900)
 /build/backend/vendor/github.com/go-pkgz/auth/provider/telegram.go:198 +0x71c
github.com/go-pkgz/auth/provider.Service.Handler(0x11dd408, 0x400064f0e0, 0x11d9b20, 0x4000596ee0, 0x400063a900)
 /build/backend/vendor/github.com/go-pkgz/auth/provider/service.go:60 +0x208
github.com/go-pkgz/auth.(*Service).Handlers.func1(0x11d9b20, 0x4000596ee0, 0x400063a900)
 /build/backend/vendor/github.com/go-pkgz/auth/auth.go:199 +0x51c
net/http.HandlerFunc.ServeHTTP(0x400091b890, 0x11d9b20, 0x4000596ee0, 0x400063a900)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-chi/chi/v5.(*Mux).Mount.func1(0x11d9b20, 0x4000596ee0, 0x400063a900)
 /build/backend/vendor/github.com/go-chi/chi/v5/mux.go:314 +0x170
net/http.HandlerFunc.ServeHTTP(0x4000596500, 0x11d9b20, 0x4000596ee0, 0x400063a900)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-chi/chi/v5/middleware.NoCache.func1(0x11d9b20, 0x4000596ee0, 0x400063a900)
 /build/backend/vendor/github.com/go-chi/chi/v5/middleware/nocache.go:54 +0x248
net/http.HandlerFunc.ServeHTTP(0x400047e378, 0x11d9b20, 0x4000596ee0, 0x400063a900)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/didip/tollbooth_chi.(*limiterWrapper).ServeHTTP(0x400047e390, 0x11d9b20, 0x4000596ee0, 0x400063a900)
 /build/backend/vendor/github.com/didip/tollbooth_chi/tollbooth_chi.go:41 +0x250
github.com/go-pkgz/rest/logger.(*Middleware).Handler.func1(0x11da270, 0x400094a0e0, 0x400063a900)
 /build/backend/vendor/github.com/go-pkgz/rest/logger/logger.go:133 +0x17c
net/http.HandlerFunc.ServeHTTP(0x40009303c0, 0x11da270, 0x400094a0e0, 0x400063a900)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-chi/chi/v5/middleware.Timeout.func1.1(0x11da270, 0x400094a0e0, 0x400063a800)
 /build/backend/vendor/github.com/go-chi/chi/v5/middleware/timeout.go:45 +0x17c
net/http.HandlerFunc.ServeHTTP(0x4000596560, 0x11da270, 0x400094a0e0, 0x400063a800)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0x40005e9840, 0x11da270, 0x400094a0e0, 0x400063a800)
 /build/backend/vendor/github.com/go-chi/chi/v5/chain.go:31 +0x4c
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x4000431d40, 0x11da270, 0x400094a0e0, 0x400063a800)
 /build/backend/vendor/github.com/go-chi/chi/v5/mux.go:442 +0x250
net/http.HandlerFunc.ServeHTTP(0x400091b8b0, 0x11da270, 0x400094a0e0, 0x400063a800)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-chi/cors.(*Cors).Handler.func1(0x11da270, 0x400094a0e0, 0x400063a800)
 /build/backend/vendor/github.com/go-chi/cors/cors.go:228 +0x19c
net/http.HandlerFunc.ServeHTTP(0x40005964c0, 0x11da270, 0x400094a0e0, 0x400063a800)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-pkgz/rest.Ping.func1(0x11da270, 0x400094a0e0, 0x400063a800)
/build/backend/vendor/github.com/go-pkgz/rest/middleware.go:51 +0x74
net/http.HandlerFunc.ServeHTTP(0x400047e2a0, 0x11da270, 0x400094a0e0, 0x400063a800)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-pkgz/rest.AppInfo.func1.1(0x11da270, 0x400094a0e0, 0x400063a800)
 /build/backend/vendor/github.com/go-pkgz/rest/middleware.go:34 +0x31c
net/http.HandlerFunc.ServeHTTP(0x400091c190, 0x11da270, 0x400094a0e0, 0x400063a800)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-pkgz/rest.Recoverer.func1.1(0x11da270, 0x400094a0e0, 0x400063a800)
 /build/backend/vendor/github.com/go-pkgz/rest/middleware.go:69 +0x98
net/http.HandlerFunc.ServeHTTP(0x4000930150, 0x11da270, 0x400094a0e0, 0x400063a800)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-chi/chi/v5/middleware.RealIP.func1(0x11da270, 0x400094a0e0, 0x400063a800)
 /build/backend/vendor/github.com/go-chi/chi/v5/middleware/realip.go:34 +0x88
net/http.HandlerFunc.ServeHTTP(0x400047e2b8, 0x11da270, 0x400094a0e0, 0x400063a800)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-chi/chi/v5/middleware.ThrottleWithOpts.func1.1(0x11da270, 0x400094a0e0, 0x400063a800)
 /build/backend/vendor/github.com/go-chi/chi/v5/middleware/throttle.go:100 +0x410
net/http.HandlerFunc.ServeHTTP(0x40005e9200, 0x11da270, 0x400094a0e0, 0x400063a800)
 /usr/local/go/src/net/http/server.go:2069 +0x40
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x4000431d40, 0x11da270, 0x400094a0e0, 0x40003b5b00)
 /build/backend/vendor/github.com/go-chi/chi/v5/mux.go:88 +0x284
net/http.serverHandler.ServeHTTP(0x400094a000, 0x11da270, 0x400094a0e0, 0x40003b5b00)
 /usr/local/go/src/net/http/server.go:2887 +0xbc
net/http.(*conn).serve(0x40008ea000, 0x11dd280, 0x40003e3780)
 /usr/local/go/src/net/http/server.go:1952 +0x71c
created by net/http.(*Server).Serve
 /usr/local/go/src/net/http/server.go:3013 +0x318
```

**Comment by holykol** [comment]
Hello. My guess is that remark integration is omitting required initialization step (i.e. calling `TelegramHandler.Run`). This issue should probably be transferred to remark repo.

**Comment by paskal** [comment]
My bad, let me fix that in remark42.
